### ISSUE TITLE
PA Review {New account creation, login, and guest/demo login}

### ISSUE THREAD

**Issue by JeffreyMJordan** [JeffreyMJordan/Genius#1]

**Comment by LochandQuay** [comment]
@JeffreyMJordan 

Console Errors:
- [x] `Warning: Invalid DOM property 'class'. Did you mean 'className'?`

Functionality Issues:
- [x] Error messages not displayed
- [x] Should have a link on forms to toggle the form ("Don't have an account? Sign Up"/"Already have an account? Log in")
- [x] `onClick` handler is on the wrong part of the nav button. I currently have to click on the text "Sign Up" or "Sign In" to get the form to show. It doesn't work if I click the surrounding whitespace.
- [x] Missing Demo Login

Styling Issues:
- [ ] Forms need more styling
    - [x] Centering everything within the form would probably help a lot.
    - [x] Input fields should be more defined...not like big bold boxes around each field, but some kind of highlighting.
    - [ ] Buttons need more work. The combination of colors, border, lack of border-radius, hover effect, and padding within the button just doesn't work. So some of the aforementioned needs to be reworked.
- [x] Nav bar after sign-in need more styling
    - [x] try hovering over the username after login 
    - [x] logout button loses partial styling

**Comment by LochandQuay** [comment]
@JeffreyMJordan 

See you made some updates:
- [x] Errors should clear on form toggle. 
- [ ] Also I think the errors would be better closer to the form.
- [x] Submit button should probably have some kind of hover effect, even if it's subtle.
- [x] Demo User should be a button, not a pre-filled sign-in form.

**Comment by LochandQuay** [comment]
@JeffreyMJordan 

- Still think the errors should be closer to the form, not way up at the top.
- Also, when I said the Demo should be a button, I mean clicking the Demo Login button should also log you in, not just fill in the fields with the credentials. 

But I'll count this as complete.
