### ISSUE TITLE
PA Review {Annotations - users can add annotations to lyrics}

### ISSUE THREAD

**Issue by JeffreyMJordan** [JeffreyMJordan/Genius#5]

**Comment by LochandQuay** [comment]
@JeffreyMJordan 

Console Errors:
- [x] (After submitting a new annotation): `Warning: Each child in an array or iterator should have a unique "key" prop.`

Functionality Issues: 
- [x] When I deleted an annotation and it was the last one, it looks like the entirety of the page refreshed...like twice. Wasn't very SPA-like.

Styling comments coming soon.

**Comment by JeffreyMJordan** [comment]
I fixed both the functionality bugs. I added a few things to the styling (Mainly making the separation between different annotations more obvious)

**Comment by LochandQuay** [comment]
@JeffreyMJordan 

- I think the fonts are a little too big in some places, and the annotation box (like the same page you can leave comments for annotations) should keep the original formatting (pre-wrap maybe?)
